In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist) #내 리스트를 전달하여 배열로 캐스팅 하는것 , 출력 결과는 객채로 변환된다

array([1, 2, 3])

In [5]:
myarray = np.array(mylist) 

In [6]:
type(myarray) # 다른 차원의 배열을 받아들일수 있다는것

numpy.ndarray

In [7]:
np.arange(0,10) # 주어진 간격 내에서균일한 간격의 값을 반환합니다. 시작과 중지 선택적 단계 크기를 제공

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)  # 0 ~ 9 까지 2의 배수

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(shape=(10,5)) # 10행 5열짜리 배열만들기  여기서 0 은 정수

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
type(0) # 0 은인트형  

int

In [13]:
type(0.0) # 0.0 은 플롯 배열이라 그럼

float

In [14]:
np.ones(shape=(2,4)) # 2,4 짜리 만듬 매개 변수를 선언할 필요가없다.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#################### 

In [20]:
np.random.seed(101)
arr = np.random.randint(0,100,10) # 0~100 까지의 난수 10개

In [21]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [22]:
arr2 = np.random.randint(0,100,10)

In [23]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [24]:
arr.max() # 최대값 알아보기

95

In [25]:
arr.argmax() # 최대값의 위치를 알아봄

0

In [26]:
arr.min() #최소값

9

In [27]:
arr.argmin() #최소값의 인덱스

7

In [28]:
arr.mean() # 어레이 평균값  

60.8

In [31]:
arr.reshape((2,5)) # 2,5 행 열로 나눠서 배열 다시하기

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [32]:
#################### 인덱싱

In [34]:
mat = np.arange(0,100).reshape(10,10)

In [35]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
row = 0 
col = 1 # 행 열 설정

In [39]:
mat[row,col] # 

1

In [40]:
mat[4,6] # 46을 프린트 하기위함 행 열에서 직접 호출이 가능

46

In [41]:
#행의 모든 항목 또는 열의 모든 항목을 가져오기

In [43]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [47]:
mat[:,1].reshape(1,10)

array([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [48]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [49]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [50]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [54]:
mat[0:3,0:3] #슬라이스

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [55]:
mat[0:3,0:7] #슬라이스

array([[ 0,  1,  2,  3,  4,  5,  6],
       [10, 11, 12, 13, 14, 15, 16],
       [20, 21, 22, 23, 24, 25, 26]])

In [56]:
mat[0:3,0:7]=0 #아래 출력결과 보기, 해당 배열을 0으로 수정

In [57]:
mat

array([[ 0,  0,  0,  0,  0,  0,  0,  7,  8,  9],
       [ 0,  0,  0,  0,  0,  0,  0, 17, 18, 19],
       [ 0,  0,  0,  0,  0,  0,  0, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [58]:
mynewmat = mat.copy()

In [60]:
mynewmat[0:6,:] = 999 # 해당배열의값을 999로 변경

In [61]:
mynewmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])